import type { ClientSettings, WorldSettings } from '../types/settings.js';

export type WorldSettingKey = keyof WorldSettings | 'formatVersion';
export type ClientSettingKey = keyof ClientSettings;

export interface SettingSchemaEntry<TValue> {
  scope: 'world' | 'client';
  config: boolean;
  type: StringConstructor | NumberConstructor | BooleanConstructor | ObjectConstructor;
  default: TValue;
  name: string;
  hint: string;
  requiresReload?: boolean;
  choices?: Record<string, string>;
  range?: {
    min: number;
    max: number;
    step: number;
  };
}

export const WORLD_SETTINGS_SCHEMA: Record<WorldSettingKey, SettingSchemaEntry<unknown>> = {
  maxDiceNumber: {
    scope: 'world',
    config: true,
    type: Number,
    default: 20,
    name: 'DICETOWER.Settings.maxDiceNumber.Name',
    hint: 'DICETOWER.Settings.maxDiceNumber.Hint',
    range: { min: 20, max: 100, step: 5 },
  },
  globalAnimationSpeed: {
    scope: 'world',
    config: true,
    type: String,
    default: '0',
    name: 'DICETOWER.Settings.globalAnimationSpeed.Name',
    hint: 'DICETOWER.Settings.globalAnimationSpeed.Hint',
    choices: {
      '0': 'DICETOWER.Settings.globalAnimationSpeed.Player',
      '1': 'DICETOWER.Settings.globalAnimationSpeed.Normal',
      '2': 'DICETOWER.Settings.globalAnimationSpeed.Fast',
      '3': 'DICETOWER.Settings.globalAnimationSpeed.VeryFast',
    },
  },
  disabledDuringCombat: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: false,
    name: 'DICETOWER.Settings.disabledDuringCombat.Name',
    hint: 'DICETOWER.Settings.disabledDuringCombat.Hint',
  },
  disabledForInitiative: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: false,
    name: 'DICETOWER.Settings.disabledForInitiative.Name',
    hint: 'DICETOWER.Settings.disabledForInitiative.Hint',
  },
  hide3dDiceOnSecretRolls: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.hide3dDiceOnSecretRolls.Name',
    hint: 'DICETOWER.Settings.hide3dDiceOnSecretRolls.Hint',
  },
  showGhostDice: {
    scope: 'world',
    config: true,
    type: String,
    default: '0',
    name: 'DICETOWER.Settings.showGhostDice.Name',
    hint: 'DICETOWER.Settings.showGhostDice.Hint',
    choices: {
      '0': 'DICETOWER.Settings.showGhostDice.Disabled',
      '1': 'DICETOWER.Settings.showGhostDice.Enabled',
      '2': 'DICETOWER.Settings.showGhostDice.OwnerOnly',
    },
  },
  hideNpcRolls: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: false,
    name: 'DICETOWER.Settings.hideNpcRolls.Name',
    hint: 'DICETOWER.Settings.hideNpcRolls.Hint',
  },
  animateRollTable: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: false,
    name: 'DICETOWER.Settings.animateRollTable.Name',
    hint: 'DICETOWER.Settings.animateRollTable.Hint',
  },
  animateInlineRoll: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.animateInlineRoll.Name',
    hint: 'DICETOWER.Settings.animateInlineRoll.Hint',
  },
  enabledSimultaneousRolls: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.enabledSimultaneousRolls.Name',
    hint: 'DICETOWER.Settings.enabledSimultaneousRolls.Hint',
    requiresReload: true,
  },
  enabledSimultaneousRollForMessage: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.enabledSimultaneousRollForMessage.Name',
    hint: 'DICETOWER.Settings.enabledSimultaneousRollForMessage.Hint',
  },
  enableDeterministicSync: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: false,
    name: 'DICETOWER.Settings.enableDeterministicSync.Name',
    hint: 'DICETOWER.Settings.enableDeterministicSync.Hint',
  },
  diceCanBeFlipped: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.diceCanBeFlipped.Name',
    hint: 'DICETOWER.Settings.diceCanBeFlipped.Hint',
  },
  allowInteractivity: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.allowInteractivity.Name',
    hint: 'DICETOWER.Settings.allowInteractivity.Hint',
  },
  immediatelyDisplayChatMessages: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: false,
    name: 'DICETOWER.Settings.immediatelyDisplayChatMessages.Name',
    hint: 'DICETOWER.Settings.immediatelyDisplayChatMessages.Hint',
  },
  forceCharacterOwnerAppearanceForInitiative: {
    scope: 'world',
    config: true,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.forceCharacterOwnerAppearanceForInitiative.Name',
    hint: 'DICETOWER.Settings.forceCharacterOwnerAppearanceForInitiative.Hint',
  },
  formatVersion: {
    scope: 'world',
    config: false,
    type: String,
    default: '',
    name: 'DICETOWER.Settings.formatVersion.Name',
    hint: 'DICETOWER.Settings.formatVersion.Hint',
  },
};

export const CLIENT_SETTINGS_SCHEMA: Record<ClientSettingKey, SettingSchemaEntry<unknown>> = {
  enabled: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.enabled.Name',
    hint: 'DICETOWER.Settings.enabled.Hint',
  },
  showExtraDice: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: false,
    name: 'DICETOWER.Settings.showExtraDice.Name',
    hint: 'DICETOWER.Settings.showExtraDice.Hint',
  },
  onlyShowOwnDice: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: false,
    name: 'DICETOWER.Settings.onlyShowOwnDice.Name',
    hint: 'DICETOWER.Settings.onlyShowOwnDice.Hint',
  },
  hideAfterRoll: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.hideAfterRoll.Name',
    hint: 'DICETOWER.Settings.hideAfterRoll.Hint',
  },
  timeBeforeHide: {
    scope: 'client',
    config: false,
    type: Number,
    default: 2000,
    name: 'DICETOWER.Settings.timeBeforeHide.Name',
    hint: 'DICETOWER.Settings.timeBeforeHide.Hint',
    range: { min: 0, max: 20000, step: 100 },
  },
  hideFX: {
    scope: 'client',
    config: false,
    type: String,
    default: 'fadeOut',
    name: 'DICETOWER.Settings.hideFX.Name',
    hint: 'DICETOWER.Settings.hideFX.Hint',
    choices: {
      fadeOut: 'DICETOWER.Settings.hideFX.FadeOut',
      none: 'DICETOWER.Settings.hideFX.None',
    },
  },
  autoscale: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.autoscale.Name',
    hint: 'DICETOWER.Settings.autoscale.Hint',
  },
  scale: {
    scope: 'client',
    config: false,
    type: Number,
    default: 75,
    name: 'DICETOWER.Settings.scale.Name',
    hint: 'DICETOWER.Settings.scale.Hint',
    range: { min: 10, max: 200, step: 1 },
  },
  speed: {
    scope: 'client',
    config: false,
    type: Number,
    default: 1,
    name: 'DICETOWER.Settings.speed.Name',
    hint: 'DICETOWER.Settings.speed.Hint',
    range: { min: 0.5, max: 3, step: 0.1 },
  },
  imageQuality: {
    scope: 'client',
    config: false,
    type: String,
    default: 'high',
    name: 'DICETOWER.Settings.imageQuality.Name',
    hint: 'DICETOWER.Settings.imageQuality.Hint',
    choices: {
      low: 'DICETOWER.Settings.imageQuality.Low',
      medium: 'DICETOWER.Settings.imageQuality.Medium',
      high: 'DICETOWER.Settings.imageQuality.High',
    },
  },
  shadowQuality: {
    scope: 'client',
    config: false,
    type: String,
    default: 'high',
    name: 'DICETOWER.Settings.shadowQuality.Name',
    hint: 'DICETOWER.Settings.shadowQuality.Hint',
    choices: {
      low: 'DICETOWER.Settings.shadowQuality.Low',
      high: 'DICETOWER.Settings.shadowQuality.High',
    },
  },
  bumpMapping: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.bumpMapping.Name',
    hint: 'DICETOWER.Settings.bumpMapping.Hint',
  },
  sounds: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.sounds.Name',
    hint: 'DICETOWER.Settings.sounds.Hint',
  },
  soundsSurface: {
    scope: 'client',
    config: false,
    type: String,
    default: 'felt',
    name: 'DICETOWER.Settings.soundsSurface.Name',
    hint: 'DICETOWER.Settings.soundsSurface.Hint',
    choices: {
      felt: 'DICETOWER.Settings.soundsSurface.Felt',
      metal: 'DICETOWER.Settings.soundsSurface.Metal',
      wood_table: 'DICETOWER.Settings.soundsSurface.WoodTable',
      wood_tray: 'DICETOWER.Settings.soundsSurface.WoodTray',
    },
  },
  soundsVolume: {
    scope: 'client',
    config: false,
    type: Number,
    default: 0.5,
    name: 'DICETOWER.Settings.soundsVolume.Name',
    hint: 'DICETOWER.Settings.soundsVolume.Hint',
    range: { min: 0, max: 1, step: 0.01 },
  },
  canvasZIndex: {
    scope: 'client',
    config: false,
    type: String,
    default: 'over',
    name: 'DICETOWER.Settings.canvasZIndex.Name',
    hint: 'DICETOWER.Settings.canvasZIndex.Hint',
    choices: {
      over: 'DICETOWER.Settings.canvasZIndex.Over',
      under: 'DICETOWER.Settings.canvasZIndex.Under',
    },
  },
  throwingForce: {
    scope: 'client',
    config: false,
    type: String,
    default: 'medium',
    name: 'DICETOWER.Settings.throwingForce.Name',
    hint: 'DICETOWER.Settings.throwingForce.Hint',
    choices: {
      weak: 'DICETOWER.Settings.throwingForce.Weak',
      medium: 'DICETOWER.Settings.throwingForce.Medium',
      strong: 'DICETOWER.Settings.throwingForce.Strong',
    },
  },
  useHighDPI: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.useHighDPI.Name',
    hint: 'DICETOWER.Settings.useHighDPI.Hint',
  },
  antialiasing: {
    scope: 'client',
    config: false,
    type: String,
    default: 'smaa',
    name: 'DICETOWER.Settings.antialiasing.Name',
    hint: 'DICETOWER.Settings.antialiasing.Hint',
    choices: {
      none: 'DICETOWER.Settings.antialiasing.None',
      smaa: 'DICETOWER.Settings.antialiasing.SMAA',
      msaa: 'DICETOWER.Settings.antialiasing.MSAA',
    },
  },
  glow: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: false,
    name: 'DICETOWER.Settings.glow.Name',
    hint: 'DICETOWER.Settings.glow.Hint',
  },
  showOthersSFX: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.showOthersSFX.Name',
    hint: 'DICETOWER.Settings.showOthersSFX.Hint',
  },
  immersiveDarkness: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: false,
    name: 'DICETOWER.Settings.immersiveDarkness.Name',
    hint: 'DICETOWER.Settings.immersiveDarkness.Hint',
  },
  muteSoundSecretRolls: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.muteSoundSecretRolls.Name',
    hint: 'DICETOWER.Settings.muteSoundSecretRolls.Hint',
  },
  enableFlavorColorset: {
    scope: 'client',
    config: false,
    type: Boolean,
    default: true,
    name: 'DICETOWER.Settings.enableFlavorColorset.Name',
    hint: 'DICETOWER.Settings.enableFlavorColorset.Hint',
  },
  rollingArea: {
    scope: 'client',
    config: false,
    type: Object,
    default: false,
    name: 'DICETOWER.Settings.rollingArea.Name',
    hint: 'DICETOWER.Settings.rollingArea.Hint',
  },
};

export const DEFAULT_WORLD_SETTINGS: WorldSettings = {
  maxDiceNumber: WORLD_SETTINGS_SCHEMA.maxDiceNumber.default as number,
  globalAnimationSpeed: WORLD_SETTINGS_SCHEMA.globalAnimationSpeed.default as string,
  disabledDuringCombat: WORLD_SETTINGS_SCHEMA.disabledDuringCombat.default as boolean,
  disabledForInitiative: WORLD_SETTINGS_SCHEMA.disabledForInitiative.default as boolean,
  hide3dDiceOnSecretRolls: WORLD_SETTINGS_SCHEMA.hide3dDiceOnSecretRolls.default as boolean,
  showGhostDice: '0' as '0' | '1' | '2',
  hideNpcRolls: WORLD_SETTINGS_SCHEMA.hideNpcRolls.default as boolean,
  animateRollTable: WORLD_SETTINGS_SCHEMA.animateRollTable.default as boolean,
  animateInlineRoll: WORLD_SETTINGS_SCHEMA.animateInlineRoll.default as boolean,
  enabledSimultaneousRolls: WORLD_SETTINGS_SCHEMA.enabledSimultaneousRolls.default as boolean,
  enabledSimultaneousRollForMessage:
    WORLD_SETTINGS_SCHEMA.enabledSimultaneousRollForMessage.default as boolean,
  enableDeterministicSync: WORLD_SETTINGS_SCHEMA.enableDeterministicSync.default as boolean,
  diceCanBeFlipped: WORLD_SETTINGS_SCHEMA.diceCanBeFlipped.default as boolean,
  allowInteractivity: WORLD_SETTINGS_SCHEMA.allowInteractivity.default as boolean,
  immediatelyDisplayChatMessages: WORLD_SETTINGS_SCHEMA.immediatelyDisplayChatMessages.default as boolean,
  forceCharacterOwnerAppearanceForInitiative:
    WORLD_SETTINGS_SCHEMA.forceCharacterOwnerAppearanceForInitiative.default as boolean,
};

export const DEFAULT_CLIENT_SETTINGS: ClientSettings = {
  enabled: CLIENT_SETTINGS_SCHEMA.enabled.default as boolean,
  showExtraDice: CLIENT_SETTINGS_SCHEMA.showExtraDice.default as boolean,
  onlyShowOwnDice: CLIENT_SETTINGS_SCHEMA.onlyShowOwnDice.default as boolean,
  hideAfterRoll: CLIENT_SETTINGS_SCHEMA.hideAfterRoll.default as boolean,
  timeBeforeHide: CLIENT_SETTINGS_SCHEMA.timeBeforeHide.default as number,
  hideFX: CLIENT_SETTINGS_SCHEMA.hideFX.default as ClientSettings['hideFX'],
  autoscale: CLIENT_SETTINGS_SCHEMA.autoscale.default as boolean,
  scale: CLIENT_SETTINGS_SCHEMA.scale.default as number,
  speed: CLIENT_SETTINGS_SCHEMA.speed.default as number,
  imageQuality: CLIENT_SETTINGS_SCHEMA.imageQuality.default as ClientSettings['imageQuality'],
  shadowQuality: CLIENT_SETTINGS_SCHEMA.shadowQuality.default as ClientSettings['shadowQuality'],
  bumpMapping: CLIENT_SETTINGS_SCHEMA.bumpMapping.default as boolean,
  sounds: CLIENT_SETTINGS_SCHEMA.sounds.default as boolean,
  soundsSurface: CLIENT_SETTINGS_SCHEMA.soundsSurface.default as ClientSettings['soundsSurface'],
  soundsVolume: CLIENT_SETTINGS_SCHEMA.soundsVolume.default as number,
  canvasZIndex: CLIENT_SETTINGS_SCHEMA.canvasZIndex.default as ClientSettings['canvasZIndex'],
  throwingForce: CLIENT_SETTINGS_SCHEMA.throwingForce.default as ClientSettings['throwingForce'],
  useHighDPI: CLIENT_SETTINGS_SCHEMA.useHighDPI.default as boolean,
  antialiasing: CLIENT_SETTINGS_SCHEMA.antialiasing.default as ClientSettings['antialiasing'],
  glow: CLIENT_SETTINGS_SCHEMA.glow.default as boolean,
  showOthersSFX: CLIENT_SETTINGS_SCHEMA.showOthersSFX.default as boolean,
  immersiveDarkness: CLIENT_SETTINGS_SCHEMA.immersiveDarkness.default as boolean,
  muteSoundSecretRolls: CLIENT_SETTINGS_SCHEMA.muteSoundSecretRolls.default as boolean,
  enableFlavorColorset: CLIENT_SETTINGS_SCHEMA.enableFlavorColorset.default as boolean,
  rollingArea: CLIENT_SETTINGS_SCHEMA.rollingArea.default as ClientSettings['rollingArea'],
};
