import type { Colorset } from '../types/appearance.js';

export const CORE_COLORSETS: Record<string, Colorset> = {
  coin_default: {
    name: 'coin_default',
    description: 'DICESONICE.ColorCoinDefault',
    category: 'DICESONICE.AcquiredTaste',
    foreground: '#f6c928',
    background: '#f6c928',
    outline: 'none',
    edge: '#f6c928',
    texture: 'metal',
    visibility: 'hidden',
  },
  spectrum_default: {
    name: 'spectrum_default',
    description: 'DICESONICE.ColorSpectrumDefault',
    category: 'DICESONICE.AcquiredTaste',
    foreground: '#ffffff',
    background: '#000000',
    outline: '#ffffff',
    edge: '#000000',
    texture: 'none',
    visibility: 'hidden',
    material: 'pristine',
  },
  radiant: {
    name: 'radiant',
    description: 'DICESONICE.ColorRadiant',
    category: 'DICESONICE.DamageTypes',
    foreground: '#F9B333',
    background: '#FFFFFF',
    outline: 'gray',
    texture: 'paper',
  },
  fire: {
    name: 'fire',
    description: 'DICESONICE.ColorFire',
    category: 'DICESONICE.DamageTypes',
    foreground: '#f8d84f',
    background: ['#f8d84f', '#f9b02d', '#f43c04', '#910200', '#4c1009'],
    outline: 'black',
    texture: 'fire',
  },
  ice: {
    name: 'ice',
    description: 'DICESONICE.ColorIce',
    category: 'DICESONICE.DamageTypes',
    foreground: '#60E9FF',
    background: ['#214fa3', '#3c6ac1', '#253f70', '#0b56e2', '#09317a'],
    outline: 'black',
    texture: 'ice',
  },
  cold: {
    name: 'cold',
    description: 'DICESONICE.ColorCold',
    category: 'DICESONICE.DamageTypes',
    foreground: '#60E9FF',
    background: ['#214fa3', '#3c6ac1', '#253f70', '#0b56e2', '#09317a'],
    outline: 'black',
    texture: 'ice_2',
  },
  poison: {
    name: 'poison',
    description: 'DICESONICE.ColorPoison',
    category: 'DICESONICE.DamageTypes',
    foreground: '#D6A8FF',
    background: ['#313866', '#504099', '#66409e', '#934fc3', '#c949fc'],
    outline: 'black',
    texture: 'cloudy',
  },
  acid: {
    name: 'acid',
    description: 'DICESONICE.ColorAcid',
    category: 'DICESONICE.DamageTypes',
    foreground: '#A9FF70',
    background: ['#a6ff00', '#83b625', '#5ace04', '#69f006', '#b0f006', '#93bc25'],
    outline: 'black',
    texture: 'marble',
    material: 'plastic',
  },
  thunder: {
    name: 'thunder',
    description: 'DICESONICE.ColorThunder',
    category: 'DICESONICE.DamageTypes',
    foreground: '#FFC500',
    background: '#7D7D7D',
    outline: 'black',
    texture: 'cloudy',
  },
  lightning: {
    name: 'lightning',
    description: 'DICESONICE.ColorLightning',
    category: 'DICESONICE.DamageTypes',
    foreground: '#FFC500',
    background: ['#f17105', '#f3ca40', '#eddea4', '#df9a57', '#dea54b'],
    outline: '#7D7D7D',
    texture: 'ice',
  },
  air: {
    name: 'air',
    description: 'DICESONICE.ColorAir',
    category: 'DICESONICE.DamageTypes',
    foreground: '#ffffff',
    background: ['#d0e5ea', '#c3dee5', '#a4ccd6', '#8dafb7', '#80a4ad'],
    outline: 'black',
    texture: 'cloudy',
  },
  water: {
    name: 'water',
    description: 'DICESONICE.ColorWater',
    category: 'DICESONICE.DamageTypes',
    foreground: '#60E9FF',
    background: ['#87b8c4', '#77a6b2', '#6b98a3', '#5b8691', '#4b757f'],
    outline: 'black',
    texture: 'water',
  },
  earth: {
    name: 'earth',
    description: 'DICESONICE.ColorEarth',
    category: 'DICESONICE.DamageTypes',
    foreground: '#6C9943',
    background: ['#346804', '#184200', '#527f22', '#3a1d04', '#56341a', '#331c17', '#5a352a', '#302210'],
    outline: 'black',
    texture: 'speckles',
  },
  force: {
    name: 'force',
    description: 'DICESONICE.ColorForce',
    category: 'DICESONICE.DamageTypes',
    foreground: 'white',
    background: ['#FF97FF', '#FF68FF', '#C651C6'],
    outline: '#570000',
    texture: 'stars',
  },
  psychic: {
    name: 'psychic',
    description: 'DICESONICE.ColorPsychic',
    category: 'DICESONICE.DamageTypes',
    foreground: '#D6A8FF',
    background: ['#313866', '#504099', '#66409E', '#934FC3', '#C949FC', '#313866'],
    outline: 'black',
    texture: 'speckles',
  },
  necrotic: {
    name: 'necrotic',
    description: 'DICESONICE.ColorNecrotic',
    category: 'DICESONICE.DamageTypes',
    foreground: '#ffffff',
    background: '#6F0000',
    outline: 'black',
    texture: 'skulls',
  },
  breebaby: {
    name: 'breebaby',
    description: 'DICESONICE.ColorPastelSunset',
    category: 'DICESONICE.ThemesSoNice',
    foreground: ['#5E175E', '#564A5E', '#45455E', '#3D5A5E', '#1E595E', '#5E3F3D', '#5E1E29', '#283C5E', '#25295E'],
    background: ['#FE89CF', '#DFD4F2', '#C2C2E8', '#CCE7FA', '#A1D9FC', '#F3C3C2', '#EB8993', '#8EA1D2', '#7477AD'],
    outline: 'white',
    texture: 'marble',
    material: 'plastic',
  },
  pinkdreams: {
    name: 'pinkdreams',
    description: 'DICESONICE.ColorPinkDreams',
    category: 'DICESONICE.ThemesSoNice',
    foreground: 'white',
    background: ['#ff007c', '#df73ff', '#f400a1', '#df00ff', '#ff33cc'],
    outline: '#570000',
    texture: 'skulls',
  },
  inspired: {
    name: 'inspired',
    description: 'DICESONICE.ColorInspired',
    category: 'DICESONICE.ThemesSoNice',
    foreground: '#FFD800',
    background: '#C4C4B6',
    outline: '#000000',
    texture: 'stone',
  },
  bloodmoon: {
    name: 'bloodmoon',
    description: 'DICESONICE.ColorBloodMoon',
    category: 'DICESONICE.ThemesSoNice',
    foreground: '#CDB800',
    background: '#6F0000',
    outline: 'black',
    texture: 'marble',
    material: 'plastic',
  },
  starynight: {
    name: 'starynight',
    description: 'DICESONICE.ColorStaryNight',
    category: 'DICESONICE.ThemesSoNice',
    foreground: '#4F708F',
    background: ['#091636', '#233660', '#4F708F', '#8597AD', '#E2E2E2'],
    outline: 'white',
    texture: 'speckles',
  },
  glitterparty: {
    name: 'glitterparty',
    description: 'DICESONICE.ColorGlitterParty',
    category: 'DICESONICE.ThemesSoNice',
    foreground: 'white',
    background: ['#FFB5F5', '#7FC9FF', '#A17FFF'],
    outline: 'none',
    texture: 'glitter',
  },
  astralsea: {
    name: 'astralsea',
    description: 'DICESONICE.ColorAstralSea',
    category: 'DICESONICE.ThemesSoNice',
    foreground: '#565656',
    background: 'white',
    outline: 'none',
    texture: 'astral',
  },
  foundry: {
    name: 'foundry',
    description: 'DICESONICE.ColorFoundry',
    category: 'DICESONICE.ThemesSoNice',
    foreground: '#000000',
    background: '#ffffff',
    outline: 'none',
    edge: '#000000',
    texture: 'radial',
  },
  dragons: {
    name: 'dragons',
    description: 'DICESONICE.ColorDragons',
    category: 'DICESONICE.AcquiredTaste',
    foreground: '#FFFFFF',
    background: ['#B80000', '#4D5A5A', '#5BB8FF', '#7E934E', '#FFFFFF', '#F6ED7C', '#7797A3', '#A78437', '#862C1A', '#FFDF8A'],
    outline: 'black',
    texture: ['dragon', 'lizard'],
  },
  birdup: {
    name: 'birdup',
    description: 'DICESONICE.ColorBirdUp',
    category: 'DICESONICE.AcquiredTaste',
    foreground: '#FFFFFF',
    background: ['#F11602', '#FFC000', '#6EC832', '#0094BC', '#05608D', '#FEABB3', '#F75680', '#F3F0DF', '#C7A57F'],
    outline: 'black',
    texture: 'bird',
  },
  tigerking: {
    name: 'tigerking',
    description: 'DICESONICE.ColorTigerKing',
    category: 'DICESONICE.AcquiredTaste',
    foreground: '#ffffff',
    background: '#FFCC40',
    outline: 'black',
    texture: ['leopard', 'tiger', 'cheetah'],
  },
  toxic: {
    name: 'toxic',
    description: 'DICESONICE.ColorToxic',
    category: 'DICESONICE.AcquiredTaste',
    foreground: '#A9FF70',
    background: ['#a6ff00', '#83b625', '#5ace04', '#69f006', '#b0f006', '#93bc25'],
    outline: 'black',
    texture: 'fire',
  },
  rainbow: {
    name: 'rainbow',
    description: 'DICESONICE.ColorRainblow',
    category: 'DICESONICE.Colors',
    foreground: ['#FF5959', '#FFA74F', '#FFFF56', '#59FF59', '#2374FF', '#00FFFF', '#FF59FF'],
    background: ['#900000', '#CE3900', '#BCBC00', '#00B500', '#00008E', '#008282', '#A500A5'],
    outline: 'black',
    texture: 'none',
  },
  random: {
    name: 'random',
    description: 'DICESONICE.ColorRaNdOm',
    category: 'DICESONICE.Colors',
    foreground: [],
    outline: [],
    background: [],
    texture: [],
  },
  black: {
    name: 'black',
    description: 'DICESONICE.ColorBlack',
    category: 'DICESONICE.Colors',
    foreground: '#ffffff',
    background: '#000000',
    outline: 'black',
    texture: 'none',
  },
  white: {
    name: 'white',
    description: 'DICESONICE.ColorWhite',
    category: 'DICESONICE.Colors',
    foreground: '#000000',
    background: '#FFFFFF',
    outline: '#FFFFFF',
    texture: 'none',
  },
  grey: {
    name: 'grey',
    description: 'DICESONICE.ColorGrey',
    category: 'DICESONICE.Colors',
    foreground: '#FFFFFF',
    background: '#888888',
    outline: '#000000',
    texture: 'none',
  },
  red: {
    name: 'red',
    description: 'DICESONICE.ColorRed',
    category: 'DICESONICE.Colors',
    foreground: '#FFFFFF',
    background: '#FF0000',
    outline: 'none',
    texture: 'none',
  },
  blue: {
    name: 'blue',
    description: 'DICESONICE.ColorBlue',
    category: 'DICESONICE.Colors',
    foreground: '#FFFFFF',
    background: '#0000FF',
    outline: 'none',
    texture: 'none',
  },
  green: {
    name: 'green',
    description: 'DICESONICE.ColorGreen',
    category: 'DICESONICE.Colors',
    foreground: '#FFFFFF',
    background: '#00FF00',
    outline: 'none',
    texture: 'none',
  },
  yellow: {
    name: 'yellow',
    description: 'DICESONICE.ColorYellow',
    category: 'DICESONICE.Colors',
    foreground: '#000000',
    background: '#FFFF00',
    outline: 'none',
    texture: 'none',
  },
  pink: {
    name: 'pink',
    description: 'DICESONICE.ColorPink',
    category: 'DICESONICE.Colors',
    foreground: '#FFFFFF',
    background: '#FF00FF',
    outline: 'none',
    texture: 'none',
  },
  cyan: {
    name: 'cyan',
    description: 'DICESONICE.ColorCyan',
    category: 'DICESONICE.Colors',
    foreground: '#000000',
    background: '#00FFFF',
    outline: 'none',
    texture: 'none',
  },
  prism: {
    name: 'prism',
    description: 'DICESONICE.ColorPrism',
    category: 'DICESONICE.AcquiredTaste',
    foreground: '#FFFFFF',
    background: '#FFFFFF',
    outline: 'black',
    texture: 'stainedglass',
  },
  bronze: {
    name: 'bronze',
    description: 'DICESONICE.ColorBronze',
    category: 'DICESONICE.ThemesSoNice',
    foreground: ['#FF9159', '#FFB066', '#FFBF59', '#FFD059'],
    background: ['#705206', '#7A4E06', '#643100', '#7A2D06'],
    outline: ['#3D2D03', '#472D04', '#301700', '#471A04'],
    edge: ['#FF5D0D', '#FF7B00', '#FFA20D', '#FFBA0D'],
    texture: ['bronze01', 'bronze02', 'bronze03', 'bronze03b', 'bronze03b', 'bronze04'],
  },
  custom: {
    name: 'custom',
    description: 'DICESONICE.ColorCustom',
    category: 'DICESONICE.Colors',
    foreground: '',
    background: '',
    outline: '',
    edge: '',
    texture: 'none',
  },
};

export const DEFAULT_COLORSET_NAME = 'custom';

export function cloneColorset(colorset: Colorset): Colorset {
  return {
    ...colorset,
    foreground: Array.isArray(colorset.foreground) ? [...colorset.foreground] : colorset.foreground,
    background: Array.isArray(colorset.background) ? [...colorset.background] : colorset.background,
    outline: Array.isArray(colorset.outline) ? [...colorset.outline] : colorset.outline,
    edge: Array.isArray(colorset.edge) ? [...colorset.edge] : colorset.edge,
    texture: Array.isArray(colorset.texture) ? [...colorset.texture] : colorset.texture,
  };
}

export function chooseRandomValue(value: string | string[] | undefined, random: () => number = Math.random): string {
  if (Array.isArray(value)) {
    if (value.length === 0) return '';
    const index = Math.floor(random() * value.length);
    return value[index] ?? '';
  }
  return value ?? '';
}

export function getDefaultColorsets(): Record<string, Colorset> {
  return Object.fromEntries(
    Object.entries(CORE_COLORSETS).map(([id, set]) => [id, cloneColorset(set)]),
  );
}
